services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # echo ${USER}
        - USER=${USER}
        # Configure git
        - GIT_NAME=Jose Lopes
        - GIT_EMAIL=lopes.joseps@gmail.com
    volumes:
      - type: bind
        source: $HOME/code
        target: /code
      - type: bind
        source: $HOME/.ssh
        target: /home/${USER}/.ssh
      - vscode-server:/home/${USER}/.vscode-server
      - zsh-history:/home/${USER}/.zsh_history
    user: root
    ports:
      - "2999:22"
      - "3001:3001"
    privileged: true # Allow debugging
    command: /usr/sbin/sshd -D
    #command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server:
