services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # echo ${USER}
        - USER=${USER}
        # Configure git
        - GIT_NAME=Jose Lopes
        - GIT_EMAIL=pedro.fraiao2@gmail.com
    volumes:
      - type: bind
        source: $HOME/code
        target: /code
      - type: bind
        source: $HOME/.ssh
        target: /home/${USER}/.ssh
    user: root
    ports:
      - "2999:22"
    command: /usr/sbin/sshd -D
    #command: /bin/sh -c "while sleep 1000; do :; done"
